scan estimation orchestrator
openclarity/vmclarity pull request #560
Opened 2023-08-16 12:07 UTC by fishkerez

## Description

https://github.com/openclarity/vmclarity/discussions/465

Continuing the apiserver PR: https://github.com/openclarity/vmclarity/pull/559

Adds 2 new reconcile controllers for ScanEstimation and AssetScanEstimation.

The cost calculation implementation for AWS will be added soon.

## Type of Change

[ ] Bug Fix  
[* ] New Feature  
[ ] Breaking Change  
[ ] Refactor  
[ ] Documentation  
[ ] Other (please describe)

2023-08-22 13:48 UTC, Tehsmash commented
@fishkerez if you rebase this PR onto the API server one and leave this in draft there is no need for a feature branch, and we can review just the top commits for each part of the commit chain. That will make all the CI work and the top of the chain testable, and allow us to merge things directly to main without having to have a second pull request to merge it all in later.

2023-08-22 15:12 UTC, Tehsmash requested changes

2023-08-22 15:12 UTC, Tehsmash commented on pkg/orchestrator/scanestimationwatcher/watcher.go
> +	}
This should be a relationship to an asset in the system, we should not be duplicating any asset information in the AssetScanEstimation.

2023-08-23 08:19 UTC, fishkerez commented
> @fishkerez if you rebase this PR onto the API server one and leave this in draft there is no need for a feature branch, and we can review just the top commits for each part of the commit chain. That will make all the CI work and the top of the chain testable, and allow us to merge things directly to main without having to have a second pull request to merge it all in later.

I will open a new PR after I will finish the work on. the

2023-08-29 09:58 UTC, fishkerez commented on pkg/orchestrator/scanestimationwatcher/watcher.go
> +	}
Took it from scanWatcher reconcile logic.

2023-08-29 11:44 UTC, fishkerez commented
Moved to  https://github.com/openclarity/vmclarity/pull/603

2023-08-29 11:44 UTC, closed without merging