feat(api): add provider ids to asset and to asset scan
openclarity/vmclarity pull request #726
Opened 2023-09-29 14:10 UTC by paralta

## Description

Last change to close Issue https://github.com/openclarity/vmclarity/issues/637, blocked by PR https://github.com/openclarity/vmclarity/pull/714 (only last 2 commits are actually for the current PR).

Please find feature design details in discussion https://github.com/openclarity/vmclarity/discussions/581.

## Type of Change

[ ] Bug Fix  
[x] New Feature  
[ ] Breaking Change  
[ ] Refactor  
[ ] Documentation  
[ ] Other (please describe)  

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/openclarity/vmclarity/blob/main/CONTRIBUTING.md)
- [x] Existing issues have been referenced (where applicable)
- [x] I have verified this change is not present in other open pull requests
- [ ] Functionality is documented
- [x] All code style checks pass
- [ ] New code contribution is covered by automated tests
- [x] All new and existing tests pass

2023-10-02 08:28 UTC, Tehsmash requested changes

2023-10-02 08:28 UTC, Tehsmash commented on api/openapi.yaml
> +          description: Provider ID of the provider responsible for picking up and running the asset scan.
I think this should really be a relationship to a provider (`$ref: "...../ProviderRelationship`) not simply the id to allow it to be $expand-able in the API.

2023-10-02 08:28 UTC, Tehsmash commented on api/openapi.yaml
> +                type: string
Similarly I think this should be an array of ProviderRelationships, which will allow them to be $expand-able in the API.

2023-10-04 11:45 UTC, akpsgit approved these changes

2023-10-04 14:34 UTC, paralta commented
@Tehsmash can you please review this one? it is blocked with your change request

2023-10-04 15:05 UTC, Tehsmash approved these changes

2023-10-04 15:29 UTC, merged