Update README.md
openclarity/vmclarity pull request #869
Opened 2023-10-30 14:39 UTC by fekete-robert

Replace logo with new Openclarity logo and add a link to the openclarity site

2023-10-30 15:31 UTC, martonsereg requested changes
We don't want the project to be renamed from VMClarity to Vm Security, and this change suggests that. We can still refer to it as VmClarity in the readme here.

We can on the other hand make a 1-sentence mention of OpenClarity and that VmClarity is part of that - and we'll change it later once we get to a unified platform.

2023-11-07 12:08 UTC, fekete-robert commented
@martonsereg I've fixed the unneeded renaming

2023-11-07 19:23 UTC, lgecse commented on README.md
> +VMClarity is now part of the [Openclarity platform](https://openclarity.io).
Please use the `OpenClarity` name instead of `Openclarity`.

2023-11-07 19:24 UTC, lgecse commented on README.md
> +  <img alt="Openclarity logo" src="https://docs.openclarity.io/img/color-logo/logo.svg" width="50%">
```suggestion
  <img alt="OpenClarity logo" src="https://docs.openclarity.io/img/color-logo/logo.svg" width="50%">
```

2023-11-08 10:13 UTC, lgecse approved these changes

2024-02-22 10:35 UTC, ramizpolic commented
Outdated, closing this one as we will have to address this separately later on. Thanks!

2024-02-22 10:35 UTC, closed without merging