Calculate completed scans count correctly
openclarity/vmclarity pull request #898
Opened 2023-11-03 10:46 UTC by adamtagscherer

## Description

Fix for: https://github.com/openclarity/vmclarity/issues/894
Fixes the aforementioned issue, for further information check issue.

## Type of Change

[x] Bug Fix  
[ ] New Feature  
[ ] Breaking Change  
[x] Refactor  
[ ] Documentation  
[ ] Other (please describe)  

## Checklist

- [ ] I have read the [contributing guidelines](https://github.com/openclarity/vmclarity/blob/main/CONTRIBUTING.md)
- [ ] Existing issues have been referenced (where applicable)
- [ ] I have verified this change is not present in other open pull requests
- [ ] Functionality is documented
- [ ] All code style checks pass
- [ ] New code contribution is covered by automated tests
- [ ] All new and existing tests pass

2023-11-03 12:04 UTC, paralta approved these changes
LGTM 👍  thanks for fixing this!

2023-11-03 12:04 UTC, lgecse approved these changes
LGTM, thanks @adamtagscherer! :)

2023-11-03 13:46 UTC, gallotamas commented on ui/src/layout/Dashboard/CounterDisplay/index.js
> +    }, [data])
This logic can be simplified:
```suggestion
    const completedScans = useMemo(
        () => data?.items.filter(item => item.state === "Aborted" || item.state === "Failed" || item.state === "Done").length ?? 0,
        [data]
    );
```

2023-11-03 14:55 UTC, gallotamas approved these changes

2023-11-03 14:56 UTC, gallotamas approved these changes

2023-11-03 15:08 UTC, Tehsmash requested changes
I think we should be using the $filter here instead of loading every scan into the UI and then filtering it. e.g. 
```
$filter=state eq 'Aborted' or state eq 'Failed' or state eq 'Done'
```

2023-11-03 15:38 UTC, gallotamas approved these changes

2023-11-03 16:35 UTC, Tehsmash approved these changes

2023-11-03 17:07 UTC, merged

2023-11-06 08:52 UTC, akpsgit commented
I see that "Risky Findings" was changed to "Findings" in https://github.com/openclarity/vmclarity/pull/898/files#diff-a7f123acafc6f879519bf54b3e58eb3ebab608f6d1c23a8107b883eee501e8cfR18

The idea was not to count packages, but only findings with Risks.

2023-11-07 14:02 UTC, adamtagscherer commented
> I see that "Risky Findings" was changed to "Findings" in https://github.com/openclarity/vmclarity/pull/898/files#diff-a7f123acafc6f879519bf54b3e58eb3ebab608f6d1c23a8107b883eee501e8cfR18
> 
> The idea was not to count packages, but only findings with Risks. Also, maybe worth making such changes if needed in a separated PR.

The problem with this was that the label said "Risky Findings" although we queried every finding without narrowing the query at all.
We can change this query to only GET the Risky Findings but then we have to decide which Findings are risky, so what is the definition of a Risky Finding?