docs: add rfc for e2e type safety
openclarity/vmclarity pull request #946
Opened 2023-11-15 09:48 UTC by gallotamas

## Description

Please read the RFC for more details.

## Type of Change

[ ] Bug Fix  
[ ] New Feature  
[ ] Breaking Change  
[ ] Refactor  
[x] Documentation  
[ ] Other (please describe)  

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/openclarity/vmclarity/blob/main/CONTRIBUTING.md)
- [x] Existing issues have been referenced (where applicable)
- [x] I have verified this change is not present in other open pull requests
- [x] Functionality is documented
- [x] All code style checks pass
- [x] New code contribution is covered by automated tests
- [x] All new and existing tests pass

2023-11-16 12:14 UTC, Tehsmash requested changes

2023-11-16 12:14 UTC, Tehsmash commented on rfc/end-to-end-type-safe-apis.md
> +    ```
too many spaces here in the markdown and in the following sections which is screwing with the code highlighting etc. You'll also want to put a newline between the code block and the other text so that it formats correctly.

2023-11-16 12:40 UTC, gallotamas commented on rfc/end-to-end-type-safe-apis.md
> +    ```
I've updated the indentation but it didn't change anything on code highlighting. Code highlighting for TS works for me with both the previous and the current version.

2023-11-16 12:43 UTC, chrisgacsal approved these changes
LGTM!

2023-11-21 14:41 UTC, ramizpolic approved these changes

2023-11-21 14:57 UTC, gallotamas commented
@Tehsmash Would you like me to change something in this RFC or can I merge it and can we plan it in the future?

2023-11-21 15:04 UTC, Tehsmash approved these changes
> @Tehsmash Would you like me to change something in this RFC or can I merge it and can we plan it in the future?

No I think its good as is, sorry for the delay re-reviewing it.

2023-11-21 15:48 UTC, merged