refactor(status): rework AssetScan General status
openclarity/vmclarity pull request #981
Opened 2023-11-28 09:20 UTC by adamtagscherer

## Description

Please provide a meaningful description of what this change will do, or is for. Bonus points for including links to
related issues, other PRs, or technical references.

Note that by _not_ including a description, you are asking reviewers to do extra work to understand the context of this
change, which may lead to your PR taking much longer to review, or result in it not being reviewed at all.

## Type of Change

[ ] Bug Fix  
[ ] New Feature  
[ ] Breaking Change  
[ ] Refactor  
[ ] Documentation  
[ ] Other (please describe)  

## Checklist

- [ ] I have read the [contributing guidelines](https://github.com/openclarity/vmclarity/blob/main/CONTRIBUTING.md)
- [ ] Existing issues have been referenced (where applicable)
- [ ] I have verified this change is not present in other open pull requests
- [ ] Functionality is documented
- [ ] All code style checks pass
- [ ] New code contribution is covered by automated tests
- [ ] All new and existing tests pass

2023-12-06 15:53 UTC, ramizpolic commented on api/models/assetscanstatus.go
> +	if a.Message == nil && as.Message != nil {
nit: reusing the condition order makes it clearer
```suggestion
	if as.Message != nil && a.Message == nil {
```

2023-12-06 16:42 UTC, ramizpolic submitted a review, later dismissed
Well done on the overall design and implementation, looks great! 🚀

2023-12-08 11:42 UTC, chrisgacsal requested changes

2023-12-08 11:42 UTC, chrisgacsal commented on api/openapi.yaml
> +            | Done        | Done           | Scan finished successfully                   |
```suggestion
            | Pending     | Created        | Scan is pending as it has been newly created                  |
            | Scheduled   | Provisioning      | Scan is scheduled as Asset resources are being provisioned                  |
            | ReadyToScan | UnSupervised | Scan is created manually without the involvement of the Orchestrator (e.g. CI/CD scenario)     |
            | ReadyToScan | ReasourcesReady    | Scan is ready to scan as Asset resources have been provisioned |
            | InProgress  | ScannerIsRunning     | Scan is in progress as Scanner is still performing scanning on Asset resources             |
            | Aborted     | Cancellation       | Scan has been aborted due to cancellation request                     |
            | Aborted     | Timeout        | Scan has been aborted due to timeout                    |
            | Failed      | Error         | Scan has failed to to one or more errors reported by the Scanner           |
            | Failed      | AbortTimeout  | Scan has failed due to being in Aborted state too long  |
            | Done        | Success           | Scan has finished successfully                |
```

2023-12-08 11:42 UTC, chrisgacsal commented on api/models/assetscanstatus.go
> +}
Would be great to add a helper method which indicates if the state reached the end of the workflow.
Something like this:
```go
func (as *AssetScanStatus) Finished() bool {
	switch as {
        case AssetScanStatusReasonDone, AssetScanStatusReasonFailed:
            return true
        default:
            return false
}
```

2023-12-12 16:59 UTC, chrisgacsal reviewed
LGTM! :shipit:

2023-12-12 16:59 UTC, chrisgacsal approved these changes

2023-12-12 17:20 UTC, merged